import prisma from '../src/config/prisma';
import { ProductCondition } from '@prisma/client';

export async function seedProcurement() {
  console.log('🏭 [SEED] Starting Bulk Procurement Module Database Seed...');

  // 1. Ensure Brands exist
  const brandList = [
    { name: 'Bosch', slug: 'bosch', country: 'Germany', isOem: true, logoUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=200' },
    { name: 'Exide', slug: 'exide', country: 'India', isOem: true, logoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200' },
    { name: 'Brembo', slug: 'brembo', country: 'Italy', isOem: false, logoUrl: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?w=200' },
    { name: 'Uno Minda', slug: 'uno-minda', country: 'India', isOem: true, logoUrl: null },
    { name: 'Lumax', slug: 'lumax', country: 'India', isOem: true, logoUrl: null },
    { name: 'Amaron', slug: 'amaron', country: 'India', isOem: true, logoUrl: null },
    { name: 'Castrol', slug: 'castrol', country: 'United Kingdom', isOem: false, logoUrl: null },
    { name: 'ZF', slug: 'zf', country: 'Germany', isOem: true, logoUrl: null },
    { name: 'Valeo', slug: 'valeo', country: 'France', isOem: true, logoUrl: null },
    { name: 'Denso', slug: 'denso', country: 'Japan', isOem: true, logoUrl: null },
    { name: 'NGK', slug: 'ngk', country: 'Japan', isOem: true, logoUrl: null },
    { name: 'SKF', slug: 'skf', country: 'Sweden', isOem: true, logoUrl: null },
    { name: 'Tata Motors Genuine', slug: 'tata-motors-genuine', country: 'India', isOem: true, logoUrl: null },
    { name: 'Maruti Suzuki Genuine', slug: 'maruti-suzuki-genuine', country: 'India', isOem: true, logoUrl: null },
  ];

  const brandsMap = new Map<string, any>();
  for (const b of brandList) {
    const brand = await prisma.brand.upsert({
      where: { slug: b.slug },
      update: { logoUrl: b.logoUrl },
      create: b,
    });
    brandsMap.set(b.name, brand);
  }

  // 2. Ensure Categories exist
  const categoriesList = [
    { name: 'Engine Components', slug: 'engine-components', description: 'Cylinder heads, pistons, spark plugs, timing belts' },
    { name: 'Brake System', slug: 'brake-system', description: 'Brake pads, rotors, drums, calipers, master cylinders' },
    { name: 'Electrical', slug: 'electrical', description: 'Alternators, starters, wiring harnesses, relays, switches' },
    { name: 'Battery', slug: 'battery', description: 'Automotive and two-wheeler high-cranking lead acid & VRLA batteries' },
    { name: 'Lighting', slug: 'lighting', description: 'Headlamps, tail lights, fog lamps, LED upgrade kits' },
    { name: 'Suspension', slug: 'suspension', description: 'Shock absorbers, struts, coil springs, lower arms' },
    { name: 'Steering', slug: 'steering', description: 'Steering racks, tie rod ends, power steering pumps' },
    { name: 'Cooling System', slug: 'cooling-system', description: 'Radiators, water pumps, coolant expansion tanks, fans' },
    { name: 'Filters', slug: 'filters', description: 'Oil filters, air filters, fuel filters, cabin filters' },
    { name: 'Lubricants', slug: 'lubricants', description: 'Engine oil, transmission fluid, brake fluid, grease' },
    { name: 'Sensors', slug: 'sensors', description: 'Oxygen sensors, MAP/MAF sensors, ABS wheel speed sensors' },
    { name: 'Clutch & Transmission', slug: 'clutch-transmission', description: 'Clutch plates, pressure plates, release bearings, flywheels' },
    { name: 'Exhaust', slug: 'exhaust', description: 'Mufflers, catalytic converters, exhaust manifolds' },
    { name: 'Accessories', slug: 'accessories', description: 'Floor mats, wipers, horn sets, body covers' },
    { name: 'Audio / Music Systems', slug: 'audio-systems', description: 'Speakers, amplifiers, head units, subwoofers' },
    { name: 'Body Parts', slug: 'body-parts', description: 'Bumpers, fenders, bonnet hoods, mirrors' },
    { name: 'Tyres', slug: 'tyres', description: 'All-season, highway-terrain and run-flat tyres' },
    { name: 'Other', slug: 'other', description: 'Hardware, clips, fasteners, general workshop consumables' },
  ];

  const categoriesMap = new Map<string, any>();
  for (const c of categoriesList) {
    const cat = await prisma.category.upsert({
      where: { slug: c.slug },
      update: {},
      create: c,
    });
    categoriesMap.set(c.name, cat);
  }

  // 3. Vehicles Setup (Makes, Models, Variants)
  const tataMake = await prisma.vehicleMake.upsert({
    where: { name: 'Tata' },
    update: {},
    create: { name: 'Tata', type: 'CAR' },
  });

  const nexonModel = await prisma.vehicleModel.upsert({
    where: { makeId_name: { makeId: tataMake.id, name: 'Nexon' } },
    update: {},
    create: { makeId: tataMake.id, name: 'Nexon', type: 'CAR' },
  });

  const nexonVariant = await prisma.vehicleVariant.upsert({
    where: { modelId_name_year_fuelType: { modelId: nexonModel.id, name: 'XZ 1.2 Petrol', year: 2023, fuelType: 'PETROL' } },
    update: {},
    create: { modelId: nexonModel.id, name: 'XZ 1.2 Petrol', year: 2023, fuelType: 'PETROL', engineCC: 1199 },
  });

  const marutiMake = await prisma.vehicleMake.upsert({
    where: { name: 'Maruti Suzuki' },
    update: {},
    create: { name: 'Maruti Suzuki', type: 'CAR' },
  });

  const swiftModel = await prisma.vehicleModel.upsert({
    where: { makeId_name: { makeId: marutiMake.id, name: 'Swift' } },
    update: {},
    create: { makeId: marutiMake.id, name: 'Swift', type: 'CAR' },
  });

  const swiftVariant = await prisma.vehicleVariant.upsert({
    where: { modelId_name_year_fuelType: { modelId: swiftModel.id, name: 'VXi 1.2L', year: 2022, fuelType: 'PETROL' } },
    update: {},
    create: { modelId: swiftModel.id, name: 'VXi 1.2L', year: 2022, fuelType: 'PETROL', engineCC: 1197 },
  });

  const hyundaiMake = await prisma.vehicleMake.upsert({
    where: { name: 'Hyundai' },
    update: {},
    create: { name: 'Hyundai', type: 'CAR' },
  });

  const cretaModel = await prisma.vehicleModel.upsert({
    where: { makeId_name: { makeId: hyundaiMake.id, name: 'Creta' } },
    update: {},
    create: { makeId: hyundaiMake.id, name: 'Creta', type: 'CAR' },
  });

  const cretaVariant = await prisma.vehicleVariant.upsert({
    where: { modelId_name_year_fuelType: { modelId: cretaModel.id, name: 'SX 1.5 MPI', year: 2023, fuelType: 'PETROL' } },
    update: {},
    create: { modelId: cretaModel.id, name: 'SX 1.5 MPI', year: 2023, fuelType: 'PETROL', engineCC: 1497 },
  });

  const hondaBikeMake = await prisma.vehicleMake.upsert({
    where: { name: 'Honda 2-Wheelers' },
    update: {},
    create: { name: 'Honda 2-Wheelers', type: 'SCOOTER' },
  });

  const activaModel = await prisma.vehicleModel.upsert({
    where: { makeId_name: { makeId: hondaBikeMake.id, name: 'Activa 6G' } },
    update: {},
    create: { makeId: hondaBikeMake.id, name: 'Activa 6G', type: 'SCOOTER' },
  });

  const activaVariant = await prisma.vehicleVariant.upsert({
    where: { modelId_name_year_fuelType: { modelId: activaModel.id, name: 'Standard 110cc', year: 2023, fuelType: 'PETROL' } },
    update: {},
    create: { modelId: activaModel.id, name: 'Standard 110cc', year: 2023, fuelType: 'PETROL', engineCC: 109 },
  });

  // 4. Seed Suppliers (Realistic Demo Suppliers)
  const suppliersSeedData = [
    {
      name: 'Bosch Automotive Aftermarket Hub',
      slug: 'bosch-india-hub',
      contactPerson: 'Rajesh Sharma',
      email: 'procurement@bosch-demo.in',
      phone: '+91 80 6657 1111',
      address: 'Hosur Road, Adugodi',
      city: 'Bengaluru',
      state: 'Karnataka',
      gstNumber: '29AABCB1234F1Z8',
      supplierType: 'MANUFACTURER',
      logoUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=200',
      categories: ['Brake System', 'Engine Components', 'Electrical', 'Filters', 'Sensors'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Exide Industries National Hub',
      slug: 'exide-power-hub',
      contactPerson: 'Amitava Banerjee',
      email: 'orders@exide-demo.in',
      phone: '+91 33 2283 2121',
      address: '59E Chowringhee Road',
      city: 'Kolkata',
      state: 'West Bengal',
      gstNumber: '19AAACE4567G1Z2',
      supplierType: 'MANUFACTURER',
      logoUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200',
      categories: ['Battery', 'Electrical'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Brembo Brake Systems India',
      slug: 'brembo-india-hub',
      contactPerson: 'Marco Moretti',
      email: 'b2b@brembo-demo.in',
      phone: '+91 20 6712 3456',
      address: 'Chakan Industrial Area Phase II',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AABCB9876H1Z5',
      supplierType: 'MANUFACTURER',
      logoUrl: 'https://images.unsplash.com/photo-1600793575654-910699b5e4d4?w=200',
      categories: ['Brake System'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Uno Minda Distribution Depot',
      slug: 'uno-minda-distributor',
      contactPerson: 'Sandeep Chawla',
      email: 'bulk@unominda-demo.in',
      phone: '+91 124 229 0011',
      address: 'Sector 37, Pace City I',
      city: 'Gurugram',
      state: 'Haryana',
      gstNumber: '06AAACU3344J1Z9',
      supplierType: 'OEM_SUPPLIER',
      logoUrl: null,
      categories: ['Electrical', 'Lighting', 'Sensors', 'Accessories'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Lumax Industries Automotive Lighting',
      slug: 'lumax-auto-hub',
      contactPerson: 'Deepak Jain',
      email: 'supply@lumax-demo.in',
      phone: '+91 11 4985 7000',
      address: 'Okhla Industrial Area Phase III',
      city: 'New Delhi',
      state: 'Delhi',
      gstNumber: '07AAACL5566K1Z1',
      supplierType: 'MANUFACTURER',
      logoUrl: null,
      categories: ['Lighting', 'Electrical', 'Body Parts'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Amaron Amara Raja Energy Hub',
      slug: 'amaron-amara-raja',
      contactPerson: 'S. Ramakrishna',
      email: 'institutional@amaron-demo.in',
      phone: '+91 40 2313 9000',
      address: 'Hitech City, Madhapur',
      city: 'Hyderabad',
      state: 'Telangana',
      gstNumber: '36AAACA1122L1Z3',
      supplierType: 'MANUFACTURER',
      logoUrl: null,
      categories: ['Battery', 'Electrical'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Castrol India Industrial & Fleet Supply',
      slug: 'castrol-india-fleet',
      contactPerson: 'Kedar Joshi',
      email: 'bulkorder@castrol-demo.in',
      phone: '+91 22 6698 4100',
      address: 'Techniplex I, Goregaon West',
      city: 'Mumbai',
      state: 'Maharashtra',
      gstNumber: '27AAACC2233M1Z4',
      supplierType: 'MANUFACTURER',
      logoUrl: null,
      categories: ['Lubricants', 'Cooling System'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'ZF Aftermarket & TRW India Hub',
      slug: 'zf-aftermarket-india',
      contactPerson: 'Venkatesh R',
      email: 'orders@zf-demo.in',
      phone: '+91 44 2624 8800',
      address: 'Ambattur Industrial Estate',
      city: 'Chennai',
      state: 'Tamil Nadu',
      gstNumber: '33AAACZ7788N1Z7',
      supplierType: 'DISTRIBUTOR',
      logoUrl: null,
      categories: ['Steering', 'Suspension', 'Clutch & Transmission'],
      supportedVehicles: ['4 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Valeo Automotive India Central',
      slug: 'valeo-india-supply',
      contactPerson: 'Prakash Sundaram',
      email: 'sales@valeo-demo.in',
      phone: '+91 44 4710 5000',
      address: 'Vallam Vadagal SIPCOT Industrial Park',
      city: 'Chennai',
      state: 'Tamil Nadu',
      gstNumber: '33AAACV9900P1Z6',
      supplierType: 'OEM_SUPPLIER',
      logoUrl: null,
      categories: ['Clutch & Transmission', 'Cooling System', 'Lighting', 'Electrical'],
      supportedVehicles: ['4 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Denso India Components',
      slug: 'denso-india-supply',
      contactPerson: 'Rakesh Verma',
      email: 'b2b@denso-demo.in',
      phone: '+91 120 256 7000',
      address: 'Surajpur Industrial Area',
      city: 'Greater Noida',
      state: 'Uttar Pradesh',
      gstNumber: '09AAACD4455Q1Z8',
      supplierType: 'MANUFACTURER',
      logoUrl: null,
      categories: ['Sensors', 'Engine Components', 'Electrical', 'Cooling System'],
      supportedVehicles: ['4 Wheeler', '2 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Tata Motors Genuine Spare Parts Depot',
      slug: 'tata-motors-oem-hub',
      contactPerson: 'Milind Kulkarni',
      email: 'oemparts@tatamotors-demo.in',
      phone: '+91 20 6613 1111',
      address: 'Pimpri Logistics Hub',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAACT0011R1Z2',
      supplierType: 'OEM',
      logoUrl: null,
      categories: ['Engine Components', 'Body Parts', 'Suspension', 'Brake System', 'Filters'],
      supportedVehicles: ['4 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
    {
      name: 'Maruti Suzuki Genuine Spares Regional',
      slug: 'maruti-suzuki-genuine-hub',
      contactPerson: 'Harish Singhal',
      email: 'genuine@maruti-demo.in',
      phone: '+91 124 439 2000',
      address: 'IMT Manesar Central Warehouse',
      city: 'Gurugram',
      state: 'Haryana',
      gstNumber: '06AAACM8899S1Z5',
      supplierType: 'OEM',
      logoUrl: null,
      categories: ['Engine Components', 'Body Parts', 'Suspension', 'Brake System', 'Electrical'],
      supportedVehicles: ['4 Wheeler'],
      verificationStatus: 'VERIFIED',
      isDemo: true,
      isActive: true,
    },
  ];

  const suppliersMap = new Map<string, any>();
  for (const s of suppliersSeedData) {
    const supplier = await prisma.supplier.upsert({
      where: { slug: s.slug },
      update: {
        contactPerson: s.contactPerson,
        email: s.email,
        phone: s.phone,
        address: s.address,
        city: s.city,
        state: s.state,
        gstNumber: s.gstNumber,
        supplierType: s.supplierType,
        categories: s.categories,
        supportedVehicles: s.supportedVehicles,
        verificationStatus: s.verificationStatus,
        isDemo: s.isDemo,
        isActive: s.isActive,
      },
      create: s,
    });
    suppliersMap.set(s.slug, supplier);
  }

  // 5. Connect matching Products where existing
  const existingProducts = await prisma.product.findMany();
  const productBySku = new Map<string, any>(existingProducts.map((p) => [p.sku, p]));
  const productByName = new Map<string, any>(existingProducts.map((p) => [p.name.toLowerCase(), p]));

  // Helper to find matching Product ID
  const findProductId = (sku: string, titleHint: string) => {
    if (productBySku.has(sku)) return productBySku.get(sku).id;
    for (const [name, p] of productByName.entries()) {
      if (name.includes(titleHint.toLowerCase())) return p.id;
    }
    return null;
  };

  // 6. Define 50+ realistic Catalog Items
  // Notice: Vehicle Make & Model are separate from Spare-Part Brand!
  const catalogDefinitions = [
    // 1-5: Brake System
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Front Ceramic Brake Pad Set',
      partNumber: 'BP-TN-204',
      categoryName: 'Brake System',
      brandName: 'Bosch',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2100.0,
      bulkPrice: 1750.0,
      moq: 10,
      stockQuantity: 500,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months / 20,000 km Warranty',
      skuMatch: 'BREMBO-BP-P83024',
      nameHint: 'Brake Pad',
      tiers: [
        { min: 1, max: 9, price: 2100.0, discount: 0 },
        { min: 10, max: 49, price: 1900.0, discount: 9.52 },
        { min: 50, max: 99, price: 1750.0, discount: 16.67 },
        { min: 100, max: null, price: 1600.0, discount: 23.81 },
      ],
    },
    {
      supplierSlug: 'brembo-india-hub',
      partName: 'Brembo Premium Disc Brake Pads (Front)',
      partNumber: 'BRM-P83024N',
      categoryName: 'Brake System',
      brandName: 'Brembo',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2650.0,
      bulkPrice: 2150.0,
      moq: 10,
      stockQuantity: 320,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: '18 Months Brembo Warranty',
      skuMatch: 'BREMBO-BP-P83024',
      nameHint: 'Brake Pad',
      tiers: [
        { min: 1, max: 9, price: 2650.0, discount: 0 },
        { min: 10, max: 49, price: 2350.0, discount: 11.32 },
        { min: 50, max: 99, price: 2150.0, discount: 18.87 },
        { min: 100, max: null, price: 1950.0, discount: 26.42 },
      ],
    },
    {
      supplierSlug: 'tata-motors-oem-hub',
      partName: 'Tata Motors Genuine Front Brake Caliper Assembly',
      partNumber: 'TM-NEX-BC-09',
      categoryName: 'Brake System',
      brandName: 'Tata Motors Genuine',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 4200.0,
      bulkPrice: 3500.0,
      moq: 5,
      stockQuantity: 150,
      leadTime: '4–6 days',
      leadTimeDays: 4,
      warranty: '24 Months OEM Factory Warranty',
      skuMatch: '',
      nameHint: 'Brake',
      tiers: [
        { min: 1, max: 4, price: 4200.0, discount: 0 },
        { min: 5, max: 19, price: 3800.0, discount: 9.52 },
        { min: 20, max: null, price: 3500.0, discount: 16.67 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch High-Performance Brake Shoe Set (Rear)',
      partNumber: 'BS-MS-SW01',
      categoryName: 'Brake System',
      brandName: 'Bosch',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 1250.0,
      bulkPrice: 980.0,
      moq: 15,
      stockQuantity: 400,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 14, price: 1250.0, discount: 0 },
        { min: 15, max: 49, price: 1100.0, discount: 12.0 },
        { min: 50, max: null, price: 980.0, discount: 21.6 },
      ],
    },
    {
      supplierSlug: 'brembo-india-hub',
      partName: 'Brembo Vented Front Brake Disc Rotor (Pair)',
      partNumber: 'BRM-RD-7712',
      categoryName: 'Brake System',
      brandName: 'Brembo',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 5400.0,
      bulkPrice: 4400.0,
      moq: 6,
      stockQuantity: 180,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '24 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 5400.0, discount: 0 },
        { min: 6, max: 19, price: 4800.0, discount: 11.11 },
        { min: 20, max: null, price: 4400.0, discount: 18.52 },
      ],
    },

    // 6-10: Batteries & Power
    {
      supplierSlug: 'exide-power-hub',
      partName: 'Exide Epiq 12V 45Ah Maintenance-Free Car Battery',
      partNumber: 'EPIQ45L-BH',
      categoryName: 'Battery',
      brandName: 'Exide',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 5200.0,
      bulkPrice: 4200.0,
      moq: 10,
      stockQuantity: 300,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: '72 Months (36F + 36P) Official Warranty',
      skuMatch: 'EXIDE-EPIQ-45L',
      nameHint: 'Exide',
      tiers: [
        { min: 1, max: 9, price: 5200.0, discount: 0 },
        { min: 10, max: 29, price: 4600.0, discount: 11.54 },
        { min: 30, max: 74, price: 4350.0, discount: 16.35 },
        { min: 75, max: null, price: 4100.0, discount: 21.15 },
      ],
    },
    {
      supplierSlug: 'amaron-amara-raja',
      partName: 'Amaron Flo 12V 45Ah Heavy Duty Car Battery',
      partNumber: 'AAM-FL-545106036',
      categoryName: 'Battery',
      brandName: 'Amaron',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 4950.0,
      bulkPrice: 3950.0,
      moq: 10,
      stockQuantity: 350,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '66 Months Amaron Warranty',
      skuMatch: '',
      nameHint: 'Amaron',
      tiers: [
        { min: 1, max: 9, price: 4950.0, discount: 0 },
        { min: 10, max: 29, price: 4350.0, discount: 12.12 },
        { min: 30, max: null, price: 3950.0, discount: 20.2 },
      ],
    },
    {
      supplierSlug: 'amaron-amara-raja',
      partName: 'Amaron Pro Rider 12V 4Ah Motorcycle Battery',
      partNumber: 'AAM-PR-0BTZ5',
      categoryName: 'Battery',
      brandName: 'Amaron',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 1350.0,
      bulkPrice: 1050.0,
      moq: 20,
      stockQuantity: 600,
      leadTime: '1–3 days',
      leadTimeDays: 1,
      warranty: '48 Months Pro-Rata Warranty',
      skuMatch: 'AMARON-PR-BTZ5',
      nameHint: 'Amaron Pro Rider',
      tiers: [
        { min: 1, max: 19, price: 1350.0, discount: 0 },
        { min: 20, max: 49, price: 1180.0, discount: 12.59 },
        { min: 50, max: null, price: 1050.0, discount: 22.22 },
      ],
    },
    {
      supplierSlug: 'exide-power-hub',
      partName: 'Exide Xpress Heavy Fleet Commercial 12V 65Ah',
      partNumber: 'XP65L-HD',
      categoryName: 'Battery',
      brandName: 'Exide',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 6800.0,
      bulkPrice: 5600.0,
      moq: 5,
      stockQuantity: 120,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '36 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 4, price: 6800.0, discount: 0 },
        { min: 5, max: 19, price: 6100.0, discount: 10.29 },
        { min: 20, max: null, price: 5600.0, discount: 17.65 },
      ],
    },
    {
      supplierSlug: 'exide-power-hub',
      partName: 'Exide Bikerz VRLA 12V 5Ah Two-Wheeler Battery',
      partNumber: '12BV5L-B',
      categoryName: 'Battery',
      brandName: 'Exide',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 1420.0,
      bulkPrice: 1100.0,
      moq: 20,
      stockQuantity: 450,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '36 Months Official Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 19, price: 1420.0, discount: 0 },
        { min: 20, max: 49, price: 1250.0, discount: 11.97 },
        { min: 50, max: null, price: 1100.0, discount: 22.54 },
      ],
    },

    // 11-15: Lighting & Electrical
    {
      supplierSlug: 'lumax-auto-hub',
      partName: 'Lumax High-Beam H4 12V LED Headlight Conversion Kit',
      partNumber: 'LX-H4-8000L',
      categoryName: 'Lighting',
      brandName: 'Lumax',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 1899.0,
      bulkPrice: 1450.0,
      moq: 15,
      stockQuantity: 380,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: '24 Months Replacement Guarantee',
      skuMatch: 'LUMAX-LED-H4-65K',
      nameHint: 'Lumax',
      tiers: [
        { min: 1, max: 14, price: 1899.0, discount: 0 },
        { min: 15, max: 49, price: 1620.0, discount: 14.69 },
        { min: 50, max: null, price: 1450.0, discount: 23.64 },
      ],
    },
    {
      supplierSlug: 'uno-minda-distributor',
      partName: 'Uno Minda Dual Trumpet Symphony Horn Set (12V)',
      partNumber: 'UM-HRN-D02',
      categoryName: 'Electrical',
      brandName: 'Uno Minda',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 850.0,
      bulkPrice: 620.0,
      moq: 25,
      stockQuantity: 800,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 24, price: 850.0, discount: 0 },
        { min: 25, max: 99, price: 720.0, discount: 15.29 },
        { min: 100, max: null, price: 620.0, discount: 27.06 },
      ],
    },
    {
      supplierSlug: 'lumax-auto-hub',
      partName: 'Lumax OEM Fog Lamp Assembly Set with Harness',
      partNumber: 'LX-FL-NX09',
      categoryName: 'Lighting',
      brandName: 'Lumax',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2400.0,
      bulkPrice: 1850.0,
      moq: 10,
      stockQuantity: 240,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 9, price: 2400.0, discount: 0 },
        { min: 10, max: 29, price: 2100.0, discount: 12.5 },
        { min: 30, max: null, price: 1850.0, discount: 22.92 },
      ],
    },
    {
      supplierSlug: 'uno-minda-distributor',
      partName: 'Uno Minda Power Window Master Control Switch',
      partNumber: 'UM-SW-CRT04',
      categoryName: 'Electrical',
      brandName: 'Uno Minda',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 1750.0,
      bulkPrice: 1350.0,
      moq: 10,
      stockQuantity: 210,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 9, price: 1750.0, discount: 0 },
        { min: 10, max: 29, price: 1520.0, discount: 13.14 },
        { min: 30, max: null, price: 1350.0, discount: 22.86 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Compact Clear Advantage Wiper Blade 24"/16" Pair',
      partNumber: '3397016582',
      categoryName: 'Accessories',
      brandName: 'Bosch',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 750.0,
      bulkPrice: 520.0,
      moq: 30,
      stockQuantity: 900,
      leadTime: '1–3 days',
      leadTimeDays: 1,
      warranty: '6 Months Performance Guarantee',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 29, price: 750.0, discount: 0 },
        { min: 30, max: 99, price: 610.0, discount: 18.67 },
        { min: 100, max: null, price: 520.0, discount: 30.67 },
      ],
    },

    // 16-20: Engine & Ignition
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Super 4 Spark Plug FR78X (Set of 4)',
      partNumber: '0242232502',
      categoryName: 'Engine Components',
      brandName: 'Bosch',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 1199.0,
      bulkPrice: 850.0,
      moq: 20,
      stockQuantity: 1200,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: 'BOSCH-SP-FR78X',
      nameHint: 'Spark Plug',
      tiers: [
        { min: 1, max: 19, price: 1199.0, discount: 0 },
        { min: 20, max: 49, price: 990.0, discount: 17.43 },
        { min: 50, max: 99, price: 900.0, discount: 24.94 },
        { min: 100, max: null, price: 820.0, discount: 31.61 },
      ],
    },
    {
      supplierSlug: 'denso-india-supply',
      partName: 'Denso Iridium Power Spark Plug (Set of 4)',
      partNumber: 'IXU22-4SET',
      categoryName: 'Engine Components',
      brandName: 'Denso',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2200.0,
      bulkPrice: 1680.0,
      moq: 15,
      stockQuantity: 500,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '100,000 km Service Life Guarantee',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 14, price: 2200.0, discount: 0 },
        { min: 15, max: 49, price: 1900.0, discount: 13.64 },
        { min: 50, max: null, price: 1680.0, discount: 23.64 },
      ],
    },
    {
      supplierSlug: 'tata-motors-oem-hub',
      partName: 'Tata Motors Genuine Timing Belt Kit with Tensioner',
      partNumber: 'TM-TB-NX12',
      categoryName: 'Engine Components',
      brandName: 'Tata Motors Genuine',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 3800.0,
      bulkPrice: 3050.0,
      moq: 8,
      stockQuantity: 190,
      leadTime: '4–6 days',
      leadTimeDays: 4,
      warranty: '24 Months / 60,000 km Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 7, price: 3800.0, discount: 0 },
        { min: 8, max: 19, price: 3400.0, discount: 10.53 },
        { min: 20, max: null, price: 3050.0, discount: 19.74 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch High Pressure Fuel Pump Assembly',
      partNumber: '0445010533',
      categoryName: 'Engine Components',
      brandName: 'Bosch',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 18500.0,
      bulkPrice: 15200.0,
      moq: 3,
      stockQuantity: 60,
      leadTime: '4–7 days',
      leadTimeDays: 5,
      warranty: '24 Months Manufacturer Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 2, price: 18500.0, discount: 0 },
        { min: 3, max: 9, price: 16500.0, discount: 10.81 },
        { min: 10, max: null, price: 15200.0, discount: 17.84 },
      ],
    },
    {
      supplierSlug: 'denso-india-supply',
      partName: 'Denso Starter Motor Assembly (12V 1.0kW)',
      partNumber: 'DS-STR-SW09',
      categoryName: 'Engine Components',
      brandName: 'Denso',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 4600.0,
      bulkPrice: 3800.0,
      moq: 6,
      stockQuantity: 140,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '18 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 4600.0, discount: 0 },
        { min: 6, max: 15, price: 4150.0, discount: 9.78 },
        { min: 16, max: null, price: 3800.0, discount: 17.39 },
      ],
    },

    // 21-25: Filters
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Spin-On High Efficiency Engine Oil Filter',
      partNumber: 'F002H23942',
      categoryName: 'Filters',
      brandName: 'Bosch',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 380.0,
      bulkPrice: 240.0,
      moq: 50,
      stockQuantity: 2500,
      leadTime: '1–3 days',
      leadTimeDays: 1,
      warranty: 'Standard Service Interval Replacement',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 49, price: 380.0, discount: 0 },
        { min: 50, max: 99, price: 290.0, discount: 23.68 },
        { min: 100, max: 249, price: 260.0, discount: 31.58 },
        { min: 250, max: null, price: 230.0, discount: 39.47 },
      ],
    },
    {
      supplierSlug: 'maruti-suzuki-genuine-hub',
      partName: 'Maruti Genuine Air Filter Element',
      partNumber: '13780M79M00',
      categoryName: 'Filters',
      brandName: 'Maruti Suzuki Genuine',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 420.0,
      bulkPrice: 285.0,
      moq: 40,
      stockQuantity: 1800,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: 'OEM Verified Performance',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 39, price: 420.0, discount: 0 },
        { min: 40, max: 99, price: 330.0, discount: 21.43 },
        { min: 100, max: null, price: 285.0, discount: 32.14 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Activated Carbon Cabin AC Filter',
      partNumber: '0986AF5098',
      categoryName: 'Filters',
      brandName: 'Bosch',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 650.0,
      bulkPrice: 420.0,
      moq: 30,
      stockQuantity: 950,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: 'HEPA Grade Carbon Media',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 29, price: 650.0, discount: 0 },
        { min: 30, max: 99, price: 490.0, discount: 24.62 },
        { min: 100, max: null, price: 420.0, discount: 35.38 },
      ],
    },
    {
      supplierSlug: 'tata-motors-oem-hub',
      partName: 'Tata Motors Genuine High Pressure Fuel Filter',
      partNumber: 'TM-FF-NX20',
      categoryName: 'Filters',
      brandName: 'Tata Motors Genuine',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 850.0,
      bulkPrice: 620.0,
      moq: 20,
      stockQuantity: 620,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months OEM Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 19, price: 850.0, discount: 0 },
        { min: 20, max: 49, price: 710.0, discount: 16.47 },
        { min: 50, max: null, price: 620.0, discount: 27.06 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Two-Wheeler High Flow Engine Oil Filter',
      partNumber: 'F002H20391',
      categoryName: 'Filters',
      brandName: 'Bosch',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 220.0,
      bulkPrice: 145.0,
      moq: 50,
      stockQuantity: 3000,
      leadTime: '1–2 days',
      leadTimeDays: 1,
      warranty: 'Standard Filter Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 49, price: 220.0, discount: 0 },
        { min: 50, max: 149, price: 170.0, discount: 22.73 },
        { min: 150, max: null, price: 145.0, discount: 34.09 },
      ],
    },

    // 26-30: Lubricants & Fluids
    {
      supplierSlug: 'castrol-india-fleet',
      partName: 'Castrol Magnatec 5W-30 Full Synthetic Engine Oil (3.5L Can)',
      partNumber: 'CAS-MAG-5W30-35L',
      categoryName: 'Lubricants',
      brandName: 'Castrol',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2150.0,
      bulkPrice: 1680.0,
      moq: 15,
      stockQuantity: 750,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: 'Certified API SP / ILSAC GF-6',
      skuMatch: 'MOTUL-7100-10W40-1L',
      nameHint: 'Oil',
      tiers: [
        { min: 1, max: 14, price: 2150.0, discount: 0 },
        { min: 15, max: 49, price: 1850.0, discount: 13.95 },
        { min: 50, max: 99, price: 1720.0, discount: 20.0 },
        { min: 100, max: null, price: 1600.0, discount: 25.58 },
      ],
    },
    {
      supplierSlug: 'castrol-india-fleet',
      partName: 'Castrol Activ 4T 20W-40 3X Protection Bike Oil (1L)',
      partNumber: 'CAS-ACT-20W40-1L',
      categoryName: 'Lubricants',
      brandName: 'Castrol',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 420.0,
      bulkPrice: 295.0,
      moq: 48,
      stockQuantity: 3200,
      leadTime: '1–3 days',
      leadTimeDays: 1,
      warranty: 'Actibond Molecules Formula',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 47, price: 420.0, discount: 0 },
        { min: 48, max: 143, price: 340.0, discount: 19.05 },
        { min: 144, max: null, price: 295.0, discount: 29.76 },
      ],
    },
    {
      supplierSlug: 'castrol-india-fleet',
      partName: 'Castrol Radicool Long Life Antifreeze Coolant (1L Concentrated)',
      partNumber: 'CAS-RAD-LLC-1L',
      categoryName: 'Cooling System',
      brandName: 'Castrol',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 380.0,
      bulkPrice: 260.0,
      moq: 24,
      stockQuantity: 1100,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: 'OAT Organic Acid Technology',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 23, price: 380.0, discount: 0 },
        { min: 24, max: 71, price: 310.0, discount: 18.42 },
        { min: 72, max: null, price: 260.0, discount: 31.58 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch DOT 4 High Boiling Point Brake Fluid (500ml)',
      partNumber: '1987479106',
      categoryName: 'Brake System',
      brandName: 'Bosch',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 240.0,
      bulkPrice: 165.0,
      moq: 30,
      stockQuantity: 1500,
      leadTime: '1–3 days',
      leadTimeDays: 1,
      warranty: 'Meets FMVSS 116 DOT 4',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 29, price: 240.0, discount: 0 },
        { min: 30, max: 99, price: 195.0, discount: 18.75 },
        { min: 100, max: null, price: 165.0, discount: 31.25 },
      ],
    },
    {
      supplierSlug: 'castrol-india-fleet',
      partName: 'Castrol Transmax Manual 80W-90 Gear Oil (1L)',
      partNumber: 'CAS-TMX-80W90',
      categoryName: 'Clutch & Transmission',
      brandName: 'Castrol',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 480.0,
      bulkPrice: 340.0,
      moq: 20,
      stockQuantity: 650,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: 'Smooth Synchromesh Protection',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 19, price: 480.0, discount: 0 },
        { min: 20, max: 59, price: 390.0, discount: 18.75 },
        { min: 60, max: null, price: 340.0, discount: 29.17 },
      ],
    },

    // 31-35: Suspension & Steering
    {
      supplierSlug: 'zf-aftermarket-india',
      partName: 'Sachs (ZF) Front Gas-Charged Shock Absorber Strut',
      partNumber: 'ZF-SA-317204',
      categoryName: 'Suspension',
      brandName: 'ZF',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 3450.0,
      bulkPrice: 2750.0,
      moq: 6,
      stockQuantity: 280,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '24 Months / 40,000 km Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 3450.0, discount: 0 },
        { min: 6, max: 19, price: 3050.0, discount: 11.59 },
        { min: 20, max: null, price: 2750.0, discount: 20.29 },
      ],
    },
    {
      supplierSlug: 'zf-aftermarket-india',
      partName: 'TRW Heavy Duty Tie Rod End (Steering)',
      partNumber: 'TRW-TE-MS71',
      categoryName: 'Steering',
      brandName: 'ZF',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 890.0,
      bulkPrice: 650.0,
      moq: 15,
      stockQuantity: 450,
      leadTime: '3–4 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 14, price: 890.0, discount: 0 },
        { min: 15, max: 49, price: 750.0, discount: 15.73 },
        { min: 50, max: null, price: 650.0, discount: 26.97 },
      ],
    },
    {
      supplierSlug: 'tata-motors-oem-hub',
      partName: 'Tata Motors Genuine Lower Suspension Control Arm (Front LH/RH)',
      partNumber: 'TM-LCA-NX01',
      categoryName: 'Suspension',
      brandName: 'Tata Motors Genuine',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2800.0,
      bulkPrice: 2200.0,
      moq: 6,
      stockQuantity: 160,
      leadTime: '4–6 days',
      leadTimeDays: 4,
      warranty: '18 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 2800.0, discount: 0 },
        { min: 6, max: 19, price: 2450.0, discount: 12.5 },
        { min: 20, max: null, price: 2200.0, discount: 21.43 },
      ],
    },
    {
      supplierSlug: 'zf-aftermarket-india',
      partName: 'Lemförder (ZF) Stabilizer Link Rod Set (Front Pair)',
      partNumber: 'LEM-SL-CR09',
      categoryName: 'Suspension',
      brandName: 'ZF',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 1450.0,
      bulkPrice: 1100.0,
      moq: 10,
      stockQuantity: 320,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 9, price: 1450.0, discount: 0 },
        { min: 10, max: 29, price: 1250.0, discount: 13.79 },
        { min: 30, max: null, price: 1100.0, discount: 24.14 },
      ],
    },
    {
      supplierSlug: 'maruti-suzuki-genuine-hub',
      partName: 'Maruti Genuine Electric Power Steering (EPS) Column Assembly',
      partNumber: '48200M79M10',
      categoryName: 'Steering',
      brandName: 'Maruti Suzuki Genuine',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 14800.0,
      bulkPrice: 12200.0,
      moq: 2,
      stockQuantity: 45,
      leadTime: '5–8 days',
      leadTimeDays: 6,
      warranty: '24 Months OEM Factory Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 1, price: 14800.0, discount: 0 },
        { min: 2, max: 4, price: 13200.0, discount: 10.81 },
        { min: 5, max: null, price: 12200.0, discount: 17.57 },
      ],
    },

    // 36-40: Clutch & Transmission
    {
      supplierSlug: 'valeo-india-supply',
      partName: 'Valeo 3-Piece Clutch Kit (Plate + Cover + Release Bearing)',
      partNumber: 'VAL-828012',
      categoryName: 'Clutch & Transmission',
      brandName: 'Valeo',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 5600.0,
      bulkPrice: 4450.0,
      moq: 6,
      stockQuantity: 210,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '24 Months / 30,000 km Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 5600.0, discount: 0 },
        { min: 6, max: 19, price: 4900.0, discount: 12.5 },
        { min: 20, max: null, price: 4450.0, discount: 20.54 },
      ],
    },
    {
      supplierSlug: 'valeo-india-supply',
      partName: 'Valeo Premium Friction Clutch Disc Plate',
      partNumber: 'VAL-CD-SW22',
      categoryName: 'Clutch & Transmission',
      brandName: 'Valeo',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 2200.0,
      bulkPrice: 1700.0,
      moq: 12,
      stockQuantity: 340,
      leadTime: '3–4 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 11, price: 2200.0, discount: 0 },
        { min: 12, max: 35, price: 1900.0, discount: 13.64 },
        { min: 36, max: null, price: 1700.0, discount: 22.73 },
      ],
    },
    {
      supplierSlug: 'zf-aftermarket-india',
      partName: 'Sachs Dual Mass Flywheel Assembly',
      partNumber: 'ZF-DMF-CR15',
      categoryName: 'Clutch & Transmission',
      brandName: 'ZF',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 16500.0,
      bulkPrice: 13500.0,
      moq: 3,
      stockQuantity: 75,
      leadTime: '4–7 days',
      leadTimeDays: 5,
      warranty: '24 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 2, price: 16500.0, discount: 0 },
        { min: 3, max: 7, price: 14800.0, discount: 10.3 },
        { min: 8, max: null, price: 13500.0, discount: 18.18 },
      ],
    },
    {
      supplierSlug: 'valeo-india-supply',
      partName: 'Valeo Hydraulic Clutch Slave Cylinder',
      partNumber: 'VAL-CSC-NX01',
      categoryName: 'Clutch & Transmission',
      brandName: 'Valeo',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 1650.0,
      bulkPrice: 1250.0,
      moq: 10,
      stockQuantity: 180,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 9, price: 1650.0, discount: 0 },
        { min: 10, max: 29, price: 1420.0, discount: 13.94 },
        { min: 30, max: null, price: 1250.0, discount: 24.24 },
      ],
    },
    {
      supplierSlug: 'maruti-suzuki-genuine-hub',
      partName: 'Maruti Genuine CV Joint Axle Drive Shaft (Front RH)',
      partNumber: '44101M79M00',
      categoryName: 'Clutch & Transmission',
      brandName: 'Maruti Suzuki Genuine',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 4800.0,
      bulkPrice: 3900.0,
      moq: 5,
      stockQuantity: 110,
      leadTime: '4–6 days',
      leadTimeDays: 4,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 4, price: 4800.0, discount: 0 },
        { min: 5, max: 14, price: 4300.0, discount: 10.42 },
        { min: 15, max: null, price: 3900.0, discount: 18.75 },
      ],
    },

    // 41-45: Sensors & Cooling System
    {
      supplierSlug: 'denso-india-supply',
      partName: 'Denso Heated Oxygen (O2) Lambda Sensor',
      partNumber: 'DOX-0109',
      categoryName: 'Sensors',
      brandName: 'Denso',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2850.0,
      bulkPrice: 2200.0,
      moq: 10,
      stockQuantity: 310,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 9, price: 2850.0, discount: 0 },
        { min: 10, max: 29, price: 2450.0, discount: 14.04 },
        { min: 30, max: null, price: 2200.0, discount: 22.81 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Wheel Speed ABS Sensor (Front)',
      partNumber: '0265008544',
      categoryName: 'Sensors',
      brandName: 'Bosch',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 1450.0,
      bulkPrice: 1080.0,
      moq: 15,
      stockQuantity: 420,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 14, price: 1450.0, discount: 0 },
        { min: 15, max: 49, price: 1250.0, discount: 13.79 },
        { min: 50, max: null, price: 1080.0, discount: 25.52 },
      ],
    },
    {
      supplierSlug: 'valeo-india-supply',
      partName: 'Valeo Aluminum Engine Radiator Core with High-Density Fins',
      partNumber: 'VAL-RAD-735201',
      categoryName: 'Cooling System',
      brandName: 'Valeo',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 4200.0,
      bulkPrice: 3350.0,
      moq: 5,
      stockQuantity: 175,
      leadTime: '3–6 days',
      leadTimeDays: 4,
      warranty: '18 Months Anti-Corrosion Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 4, price: 4200.0, discount: 0 },
        { min: 5, max: 14, price: 3700.0, discount: 11.9 },
        { min: 15, max: null, price: 3350.0, discount: 20.24 },
      ],
    },
    {
      supplierSlug: 'denso-india-supply',
      partName: 'Denso Engine Radiator Cooling Fan Assembly (12V)',
      partNumber: 'DS-FAN-CR22',
      categoryName: 'Cooling System',
      brandName: 'Denso',
      vehicleMakeName: 'Hyundai',
      vehicleModelName: 'Creta',
      variantName: 'SX 1.5 MPI',
      year: 2023,
      unitPrice: 3600.0,
      bulkPrice: 2850.0,
      moq: 6,
      stockQuantity: 190,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 3600.0, discount: 0 },
        { min: 6, max: 19, price: 3200.0, discount: 11.11 },
        { min: 20, max: null, price: 2850.0, discount: 20.83 },
      ],
    },
    {
      supplierSlug: 'denso-india-supply',
      partName: 'Denso High-Accuracy Manifold Absolute Pressure (MAP) Sensor',
      partNumber: 'DS-MAP-0201',
      categoryName: 'Sensors',
      brandName: 'Denso',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 1950.0,
      bulkPrice: 1480.0,
      moq: 12,
      stockQuantity: 280,
      leadTime: '2–4 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 11, price: 1950.0, discount: 0 },
        { min: 12, max: 35, price: 1680.0, discount: 13.85 },
        { min: 36, max: null, price: 1480.0, discount: 24.1 },
      ],
    },

    // 46-52: Body Parts, Consumables & Two-Wheeler Specials
    {
      supplierSlug: 'tata-motors-oem-hub',
      partName: 'Tata Motors Genuine Front Bumper Shell (Primed for Paint)',
      partNumber: '542488000108',
      categoryName: 'Body Parts',
      brandName: 'Tata Motors Genuine',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 4800.0,
      bulkPrice: 3900.0,
      moq: 4,
      stockQuantity: 85,
      leadTime: '5–8 days',
      leadTimeDays: 6,
      warranty: 'OEM Factory Fit Guaranteed',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 3, price: 4800.0, discount: 0 },
        { min: 4, max: 9, price: 4300.0, discount: 10.42 },
        { min: 10, max: null, price: 3900.0, discount: 18.75 },
      ],
    },
    {
      supplierSlug: 'maruti-suzuki-genuine-hub',
      partName: 'Maruti Genuine Outer Rear View Mirror Assembly (Right Hand, Electric)',
      partNumber: '84701M79M20',
      categoryName: 'Body Parts',
      brandName: 'Maruti Suzuki Genuine',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 2400.0,
      bulkPrice: 1950.0,
      moq: 8,
      stockQuantity: 150,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 7, price: 2400.0, discount: 0 },
        { min: 8, max: 19, price: 2150.0, discount: 10.42 },
        { min: 20, max: null, price: 1950.0, discount: 18.75 },
      ],
    },
    {
      supplierSlug: 'lumax-auto-hub',
      partName: 'Lumax Two-Wheeler Clear Lens Headlamp Unit with Bulb',
      partNumber: 'LX-HL-ACT6G',
      categoryName: 'Lighting',
      brandName: 'Lumax',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 1250.0,
      bulkPrice: 920.0,
      moq: 20,
      stockQuantity: 520,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 19, price: 1250.0, discount: 0 },
        { min: 20, max: 59, price: 1050.0, discount: 16.0 },
        { min: 60, max: null, price: 920.0, discount: 26.4 },
      ],
    },
    {
      supplierSlug: 'uno-minda-distributor',
      partName: 'Uno Minda Handlebar Switch LH/RH Combo Set',
      partNumber: 'UM-SW-ACT02',
      categoryName: 'Electrical',
      brandName: 'Uno Minda',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 680.0,
      bulkPrice: 480.0,
      moq: 30,
      stockQuantity: 650,
      leadTime: '2–3 days',
      leadTimeDays: 2,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 29, price: 680.0, discount: 0 },
        { min: 30, max: 79, price: 560.0, discount: 17.65 },
        { min: 80, max: null, price: 480.0, discount: 29.41 },
      ],
    },
    {
      supplierSlug: 'bosch-india-hub',
      partName: 'Bosch Spark Plug UR4AC for 100cc–125cc Scooters',
      partNumber: '0241045001',
      categoryName: 'Engine Components',
      brandName: 'Bosch',
      vehicleMakeName: 'Honda 2-Wheelers',
      vehicleModelName: 'Activa 6G',
      variantName: 'Standard 110cc',
      year: 2023,
      unitPrice: 160.0,
      bulkPrice: 98.0,
      moq: 50,
      stockQuantity: 4000,
      leadTime: '1–2 days',
      leadTimeDays: 1,
      warranty: 'Standard Spark Plug Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 49, price: 160.0, discount: 0 },
        { min: 50, max: 149, price: 120.0, discount: 25.0 },
        { min: 150, max: null, price: 98.0, discount: 38.75 },
      ],
    },
    {
      supplierSlug: 'valeo-india-supply',
      partName: 'Valeo Dual Speed High Efficiency Radiator Fan Motor',
      partNumber: 'VAL-FM-NX12',
      categoryName: 'Cooling System',
      brandName: 'Valeo',
      vehicleMakeName: 'Tata',
      vehicleModelName: 'Nexon',
      variantName: 'XZ 1.2 Petrol',
      year: 2023,
      unitPrice: 2450.0,
      bulkPrice: 1950.0,
      moq: 8,
      stockQuantity: 190,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '12 Months Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 7, price: 2450.0, discount: 0 },
        { min: 8, max: 19, price: 2150.0, discount: 12.24 },
        { min: 20, max: null, price: 1950.0, discount: 20.41 },
      ],
    },
    {
      supplierSlug: 'zf-aftermarket-india',
      partName: 'Lemförder Engine Mounting Hydromount (Front Right)',
      partNumber: 'LEM-EM-SW20',
      categoryName: 'Engine Components',
      brandName: 'ZF',
      vehicleMakeName: 'Maruti Suzuki',
      vehicleModelName: 'Swift',
      variantName: 'VXi 1.2L',
      year: 2022,
      unitPrice: 2600.0,
      bulkPrice: 2050.0,
      moq: 6,
      stockQuantity: 160,
      leadTime: '3–5 days',
      leadTimeDays: 3,
      warranty: '18 Months Vibration Dampening Warranty',
      skuMatch: '',
      nameHint: '',
      tiers: [
        { min: 1, max: 5, price: 2600.0, discount: 0 },
        { min: 6, max: 15, price: 2300.0, discount: 11.54 },
        { min: 16, max: null, price: 2050.0, discount: 21.15 },
      ],
    },
  ];

  // Helper maps for vehicle entities
  const makesByName = new Map([
    ['Tata', tataMake],
    ['Maruti Suzuki', marutiMake],
    ['Hyundai', hyundaiMake],
    ['Honda 2-Wheelers', hondaBikeMake],
  ]);

  const modelsByName = new Map([
    ['Nexon', nexonModel],
    ['Swift', swiftModel],
    ['Creta', cretaModel],
    ['Activa 6G', activaModel],
  ]);

  const variantsByName = new Map([
    ['XZ 1.2 Petrol', nexonVariant],
    ['VXi 1.2L', swiftVariant],
    ['SX 1.5 MPI', cretaVariant],
    ['Standard 110cc', activaVariant],
  ]);

  console.log(`📦 Creating ${catalogDefinitions.length} supplier catalog items with bulk pricing tiers...`);

  const createdCatalogItems: any[] = [];

  for (const item of catalogDefinitions) {
    const supplier = suppliersMap.get(item.supplierSlug);
    if (!supplier) continue;

    const brand = brandsMap.get(item.brandName);
    const category = categoriesMap.get(item.categoryName);
    const make = makesByName.get(item.vehicleMakeName);
    const model = modelsByName.get(item.vehicleModelName);
    const variant = variantsByName.get(item.variantName);

    // Link product if existing
    const matchedProductId = findProductId(item.skuMatch, item.nameHint);

    // Find or create catalog item
    const existing = await prisma.supplierCatalogItem.findFirst({
      where: {
        supplierId: supplier.id,
        partNumber: item.partNumber,
      },
    });

    let catalogItem: any;
    if (existing) {
      catalogItem = await prisma.supplierCatalogItem.update({
        where: { id: existing.id },
        data: {
          partName: item.partName,
          categoryName: item.categoryName,
          categoryId: category?.id,
          brandId: brand?.id,
          brandName: item.brandName,
          vehicleMakeId: make?.id,
          vehicleMakeName: item.vehicleMakeName,
          vehicleModelId: model?.id,
          vehicleModelName: item.vehicleModelName,
          vehicleVariantId: variant?.id,
          variantName: item.variantName,
          year: item.year,
          unitPrice: item.unitPrice,
          bulkPrice: item.bulkPrice,
          moq: item.moq,
          stockQuantity: item.stockQuantity,
          warranty: item.warranty,
          leadTime: item.leadTime,
          leadTimeDays: item.leadTimeDays,
          productId: matchedProductId || existing.productId,
          isAvailable: true,
        },
      });
      // Delete old tiers and recreate
      await prisma.bulkPriceTier.deleteMany({ where: { catalogItemId: catalogItem.id } });
    } else {
      catalogItem = await prisma.supplierCatalogItem.create({
        data: {
          supplierId: supplier.id,
          productId: matchedProductId,
          partName: item.partName,
          partNumber: item.partNumber,
          categoryName: item.categoryName,
          categoryId: category?.id,
          brandId: brand?.id,
          brandName: item.brandName,
          vehicleMakeId: make?.id,
          vehicleMakeName: item.vehicleMakeName,
          vehicleModelId: model?.id,
          vehicleModelName: item.vehicleModelName,
          vehicleVariantId: variant?.id,
          variantName: item.variantName,
          year: item.year,
          condition: ProductCondition.GENUINE_NEW,
          unitPrice: item.unitPrice,
          bulkPrice: item.bulkPrice,
          moq: item.moq,
          stockQuantity: item.stockQuantity,
          warranty: item.warranty,
          leadTime: item.leadTime,
          leadTimeDays: item.leadTimeDays,
          isAvailable: true,
        },
      });
    }

    // Create Bulk Price Tiers
    for (const tier of item.tiers) {
      await prisma.bulkPriceTier.create({
        data: {
          catalogItemId: catalogItem.id,
          minQuantity: tier.min,
          maxQuantity: tier.max,
          unitPrice: tier.price,
          discountPercent: tier.discount,
        },
      });
    }

    createdCatalogItems.push(catalogItem);
  }

  // 7. Seed Initial Purchase Orders (5 realistic lifecycle orders)
  console.log('📑 Seeding 5 initial Purchase Orders representing diverse lifecycle stages...');

  const admin = await prisma.user.findFirst({ where: { role: 'ADMIN' } });
  const adminId = admin?.id || null;

  // PO 1: DRAFT (Exide Batteries)
  const exideSupplier = suppliersMap.get('exide-power-hub');
  const exideItem = createdCatalogItems.find((c) => c.supplierId === exideSupplier?.id);
  if (exideSupplier && exideItem) {
    const poNumber = 'PO-PNX-2026-0001';
    const existingPo = await prisma.purchaseOrder.findUnique({ where: { poNumber } });
    if (!existingPo) {
      await prisma.purchaseOrder.create({
        data: {
          poNumber,
          supplierId: exideSupplier.id,
          adminId,
          status: 'DRAFT',
          subtotal: 104000.0,
          bulkDiscount: 17000.0,
          tax: 15660.0, // 18% GST on 87,000
          shipping: 2500.0,
          handling: 500.0,
          totalCost: 105660.0,
          paymentMethod: 'CREDIT_TERMS',
          paymentStatus: 'PENDING',
          expectedDelivery: new Date(Date.now() + 5 * 86400000),
          notes: 'Standard replenishment batch for Q4 workshop battery stock.',
          items: {
            create: [
              {
                catalogItemId: exideItem.id,
                productId: exideItem.productId,
                partName: exideItem.partName,
                partNumber: exideItem.partNumber,
                brandName: exideItem.brandName,
                vehicleCompatibility: `${exideItem.vehicleMakeName} ${exideItem.vehicleModelName}`,
                orderedQuantity: 20,
                receivedQuantity: 0,
                unitPrice: exideItem.unitPrice,
                bulkDiscount: 17000.0,
                totalCost: 87000.0,
              },
            ],
          },
        },
      });
    }
  }

  // PO 2: PROCESSING (Uno Minda Horns & Switches)
  const mindaSupplier = suppliersMap.get('uno-minda-distributor');
  const mindaItem = createdCatalogItems.find((c) => c.supplierId === mindaSupplier?.id);
  if (mindaSupplier && mindaItem) {
    const poNumber = 'PO-PNX-2026-0002';
    const existingPo = await prisma.purchaseOrder.findUnique({ where: { poNumber } });
    if (!existingPo) {
      await prisma.purchaseOrder.create({
        data: {
          poNumber,
          supplierId: mindaSupplier.id,
          adminId,
          status: 'PROCESSING',
          subtotal: 85000.0,
          bulkDiscount: 23000.0,
          tax: 11160.0,
          shipping: 1200.0,
          handling: 300.0,
          totalCost: 74660.0,
          paymentMethod: 'BANK_TRANSFER',
          paymentStatus: 'PAID',
          supplierInvoice: 'INV-MINDA-2026-8812',
          paymentReference: 'NEFT-MNDA-9928172',
          expectedDelivery: new Date(Date.now() + 4 * 86400000),
          notes: 'Processing at Manesar plant. Inbound shipment scheduled.',
          items: {
            create: [
              {
                catalogItemId: mindaItem.id,
                productId: mindaItem.productId,
                partName: mindaItem.partName,
                partNumber: mindaItem.partNumber,
                brandName: mindaItem.brandName,
                vehicleCompatibility: `${mindaItem.vehicleMakeName} ${mindaItem.vehicleModelName}`,
                orderedQuantity: 100,
                receivedQuantity: 0,
                unitPrice: mindaItem.unitPrice,
                bulkDiscount: 23000.0,
                totalCost: 62000.0,
              },
            ],
          },
        },
      });
    }
  }

  // PO 3: IN_TRANSIT (Lumax LED Headlights)
  const lumaxSupplier = suppliersMap.get('lumax-auto-hub');
  const lumaxItem = createdCatalogItems.find((c) => c.supplierId === lumaxSupplier?.id);
  if (lumaxSupplier && lumaxItem) {
    const poNumber = 'PO-PNX-2026-0003';
    const existingPo = await prisma.purchaseOrder.findUnique({ where: { poNumber } });
    if (!existingPo) {
      await prisma.purchaseOrder.create({
        data: {
          poNumber,
          supplierId: lumaxSupplier.id,
          adminId,
          status: 'IN_TRANSIT',
          subtotal: 94950.0,
          bulkDiscount: 22450.0,
          tax: 13050.0,
          shipping: 1800.0,
          handling: 400.0,
          totalCost: 87750.0,
          paymentMethod: 'UPI',
          paymentStatus: 'PAID',
          supplierInvoice: 'INV-LMX-7721',
          paymentReference: 'UPI-LMX-001293',
          expectedDelivery: new Date(Date.now() + 2 * 86400000),
          notes: 'Dispatched via BlueDart Surface Express (AWB: BD-BLR-883921).',
          items: {
            create: [
              {
                catalogItemId: lumaxItem.id,
                productId: lumaxItem.productId,
                partName: lumaxItem.partName,
                partNumber: lumaxItem.partNumber,
                brandName: lumaxItem.brandName,
                vehicleCompatibility: `${lumaxItem.vehicleMakeName} ${lumaxItem.vehicleModelName}`,
                orderedQuantity: 50,
                receivedQuantity: 0,
                unitPrice: lumaxItem.unitPrice,
                bulkDiscount: 22450.0,
                totalCost: 72500.0,
              },
            ],
          },
        },
      });
    }
  }

  // PO 4: PARTIALLY_RECEIVED (Brembo Brake Pads for Nexon)
  const bremboSupplier = suppliersMap.get('brembo-india-hub');
  const bremboItem = createdCatalogItems.find((c) => c.supplierId === bremboSupplier?.id);
  if (bremboSupplier && bremboItem) {
    const poNumber = 'PO-PNX-2026-0004';
    let po4 = await prisma.purchaseOrder.findUnique({ where: { poNumber }, include: { items: true } });
    if (!po4) {
      po4 = await prisma.purchaseOrder.create({
        data: {
          poNumber,
          supplierId: bremboSupplier.id,
          adminId,
          status: 'PARTIALLY_RECEIVED',
          subtotal: 265000.0,
          bulkDiscount: 70000.0,
          tax: 35100.0,
          shipping: 3500.0,
          handling: 800.0,
          totalCost: 234400.0,
          paymentMethod: 'BANK_TRANSFER',
          paymentStatus: 'PARTIAL',
          supplierInvoice: 'INV-BRM-99120',
          paymentReference: 'TXN-BRM-PARTIAL-1',
          expectedDelivery: new Date(Date.now() - 1 * 86400000),
          notes: 'Batch 1 (60 units) received and quality checked. Balance 40 units due in next delivery truck.',
          items: {
            create: [
              {
                catalogItemId: bremboItem.id,
                productId: bremboItem.productId,
                partName: bremboItem.partName,
                partNumber: bremboItem.partNumber,
                brandName: bremboItem.brandName,
                vehicleCompatibility: `${bremboItem.vehicleMakeName} ${bremboItem.vehicleModelName}`,
                orderedQuantity: 100,
                receivedQuantity: 60, // 60 received, 40 remaining
                unitPrice: bremboItem.unitPrice,
                bulkDiscount: 70000.0,
                totalCost: 195000.0,
              },
            ],
          },
        },
        include: { items: true },
      });

      // Goods Receipt for the 60 units
      const grnNumber = 'GRN-2026-0001';
      const existingGrn = await prisma.goodsReceipt.findUnique({ where: { receiptNumber: grnNumber } });
      if (!existingGrn && po4.items[0]) {
        await prisma.goodsReceipt.create({
          data: {
            receiptNumber: grnNumber,
            purchaseOrderId: po4.id,
            receivedByAdminId: adminId,
            carrier: 'Dedicated Supplier Logistics',
            trackingNumber: 'TRK-BRM-8812',
            notes: 'First consignment 60 units received in good order.',
            items: {
              create: [
                {
                  poItemId: po4.items[0].id,
                  productId: bremboItem.productId,
                  quantityReceived: 60,
                },
              ],
            },
          },
        });
      }
    }
  }

  // PO 5: COMPLETED (Bosch Spark Plugs & Lubricants)
  const boschSupplier = suppliersMap.get('bosch-india-hub');
  const boschSparkPlug = createdCatalogItems.find(
    (c) => c.supplierId === boschSupplier?.id && c.partNumber === '0242232502'
  );
  if (boschSupplier && boschSparkPlug) {
    const poNumber = 'PO-PNX-2026-0005';
    let po5 = await prisma.purchaseOrder.findUnique({ where: { poNumber }, include: { items: true } });
    if (!po5) {
      po5 = await prisma.purchaseOrder.create({
        data: {
          poNumber,
          supplierId: boschSupplier.id,
          adminId,
          status: 'COMPLETED',
          subtotal: 119900.0,
          bulkDiscount: 37900.0,
          tax: 14760.0,
          shipping: 2000.0,
          handling: 500.0,
          totalCost: 99260.0,
          paymentMethod: 'BANK_TRANSFER',
          paymentStatus: 'PAID',
          supplierInvoice: 'INV-BOSCH-2026-0091',
          paymentReference: 'NEFT-BSH-554433',
          expectedDelivery: new Date(Date.now() - 7 * 86400000),
          receivedAt: new Date(Date.now() - 5 * 86400000),
          notes: 'Full order of 100 sets received, verified, and placed into central inventory.',
          items: {
            create: [
              {
                catalogItemId: boschSparkPlug.id,
                productId: boschSparkPlug.productId,
                partName: boschSparkPlug.partName,
                partNumber: boschSparkPlug.partNumber,
                brandName: boschSparkPlug.brandName,
                vehicleCompatibility: `${boschSparkPlug.vehicleMakeName} ${boschSparkPlug.vehicleModelName}`,
                orderedQuantity: 100,
                receivedQuantity: 100,
                unitPrice: boschSparkPlug.unitPrice,
                bulkDiscount: 37900.0,
                totalCost: 82000.0,
              },
            ],
          },
        },
        include: { items: true },
      });

      const grnNumber = 'GRN-2026-0002';
      const existingGrn = await prisma.goodsReceipt.findUnique({ where: { receiptNumber: grnNumber } });
      if (!existingGrn && po5.items[0]) {
        await prisma.goodsReceipt.create({
          data: {
            receiptNumber: grnNumber,
            purchaseOrderId: po5.id,
            receivedByAdminId: adminId,
            carrier: 'BlueDart Logistics',
            trackingNumber: 'BD-BSH-102938',
            receivedDate: new Date(Date.now() - 5 * 86400000),
            notes: 'All 100 units accepted into warehouse stock.',
            items: {
              create: [
                {
                  poItemId: po5.items[0].id,
                  productId: boschSparkPlug.productId,
                  quantityReceived: 100,
                },
              ],
            },
          },
        });
      }
    }
  }

  console.log('✅ [SEED] Bulk Procurement Module Seed completed successfully!');
}

// Allow direct CLI invocation
if (require.main === module) {
  seedProcurement()
    .catch((err) => {
      console.error('❌ [SEED] Error seeding procurement:', err);
      process.exit(1);
    })
    .finally(() => prisma.$disconnect());
}
