services:
  - type: web
    name: partnexa1
    runtime: static
    buildCommand: cd frontend/customer && npm ci && npm run build
    staticPublishPath: frontend/customer/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
